environment: staging
replicaCount: 2

config:
  nodeEnv: staging
  logLevel: debug

autoscaling:
  minReplicas: 2
  maxReplicas: 4

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
