apiVersion: v1
kind: Secret
metadata:
  name: {{ include "icounter-api.fullname" . }}
  labels:
    {{- include "icounter-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}
