apiVersion: v2
name: alb-controller
description: AWS Load Balancer Controller for iCOUNTER EKS
type: application
version: 0.1.0
appVersion: "2.8.4"

dependencies:
  - name: aws-load-balancer-controller
    version: "1.8.4"
    repository: "https://aws.github.io/eks-charts"
