{{- if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ index .Values "external-secrets" "serviceAccount" "name" }}
            namespace: kube-system
{{- end }}
